version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    command: >
      bash -c "
        echo 'Waiting for Elasticsearch to start...';
        sleep 30;
        /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -i Test123!;
        echo 'Password reset complete.';
        /usr/share/elasticsearch/bin/elasticsearch
      "
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-setup:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-setup
    depends_on:
      - kafka
    entrypoint: >
      /bin/bash -c "
      echo 'Waiting for Kafka to be ready...';
      sleep 20;
      if ! /usr/bin/kafka-topics --bootstrap-server kafka:9092 --list | grep -q '^my_topic$'; then
        echo 'Creating topic my_topic...';
        /usr/bin/kafka-topics --create --topic my_topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1;
        echo 'Kafka topic created.'; 
      else
        echo 'Topic my_topic already exists.';
      fi
      "

  kafka-consumer:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-consumer
    depends_on:
      - kafka
    entrypoint: >
      /bin/bash -c "
      echo 'Waiting to consume messages from my_topic...';
      sleep 20;
      kafka-console-consumer --bootstrap-server kafka:9092 --topic my_topic --from-beginning
      "
